
name: 'e2e-all'

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '15 * * * *'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/playwright-github-action@v1
      - name: Install playwright
        run: npm i -D @playwright/test
      - name: Install playwright browsers
        run: npx playwright install
      - name: Run test with WebKit
        run: npx playwright test --project=webkit
      - name: Run test with Firefox
        run: npx playwright test --project=firefox
      - name: Run test with Chromium
        run: npx playwright test --project=chromium